name = "KEGGAPI"
uuid = "e8256861-d17c-4800-bf17-838497555b93"
version = "1.0.0"
authors = ["Nicholas Geoffrion", "Maria Victoria Aguilar Pontes", "Carlos Vigil-Vásquez"]

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"

[compat]
HTTP = "1"
julia = "1.10"

[extras]
Runic = "62bfec6d-59d7-401d-8490-b29ee721c001"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Runic"]
